tio:
  core:
    server:
      # websocket port default 9876
      port: 5678
      # 心跳时间
      heartbeat-timeout: 60000
      # 集群配置 默认关闭
    cluster:
      enabled: true
      # 集群是通过redis的Pub/Sub实现，所以需要配置Redis
      redis:
        nodes: 127.0.0.1:6379
      all: true
      group: true
      ip: true
      user: true
      # SSL 配置
      ssl:
        enabled: false
        key-store:
        password:
        trust-store:
#数据库名称配置
database:
  schema: emulate_uc
server:
  port: 8081